### ISSUE TITLE
[todo-modern] doesn't work 

### ISSUE THREAD

**Issue by taven-liu** [relayjs/relay-examples#26]
```
	0 info it worked if it ends with ok
	1 verbose cli [ 'D:\\app\\develop\\nodejs\\node.exe',
	1 verbose cli   'D:\\app\\develop\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js',
	1 verbose cli   'run',
	1 verbose cli   'build' ]
	2 info using npm@4.5.0
	3 info using node@v6.10.2
	4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
	5 info lifecycle @~prebuild: @
	6 silly lifecycle @~prebuild: no script for prebuild, continuing
	7 info lifecycle @~build: @
	8 verbose lifecycle @~build: unsafe-perm in lifecycle true
	9 verbose lifecycle @~build: PATH: D:\app\develop\nodejs\node_global\node_modules\npm\bin\node-gyp-bin;D:\data\code\relay-examples\todo-modern\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;D:\app\develop\Python27\;D:\app\develop\Python27\Scripts;D:\app\com\VanDyke Software\Clients\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;d:\app\develop\Git\cmd;D:\app\develop\nodejs\;D:\app\develop\TortoiseGit\bin;C:\Users\liuxc1\AppData\Local\Microsoft\WindowsApps;C:\Users\liuxc1\AppData\Roaming\npm;D:\app\develop\nodejs\node_global
	10 verbose lifecycle @~build: CWD: D:\data\code\relay-examples\todo-modern
	11 silly lifecycle @~build: Args: [ '/d /s /c',
	11 silly lifecycle   'relay-compiler --src ./js/ --schema ./data/schema.graphql' ]
	12 silly lifecycle @~build: Returned: code: 1  signal: null
	13 info lifecycle @~build: Failed to exec build script
	14 verbose stack Error: @ build: `relay-compiler --src ./js/ --schema ./data/schema.graphql`
	14 verbose stack Exit status 1
	14 verbose stack     at EventEmitter.<anonymous> (D:\app\develop\nodejs\node_global\node_modules\npm\lib\utils\lifecycle.js:279:16)
	14 verbose stack     at emitTwo (events.js:106:13)
	14 verbose stack     at EventEmitter.emit (events.js:191:7)
	14 verbose stack     at ChildProcess.<anonymous> (D:\app\develop\nodejs\node_global\node_modules\npm\lib\utils\spawn.js:40:14)
	14 verbose stack     at emitTwo (events.js:106:13)
	14 verbose stack     at ChildProcess.emit (events.js:191:7)
	14 verbose stack     at maybeClose (internal/child_process.js:886:16)
	14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
	15 verbose pkgid @
	16 verbose cwd D:\data\code\relay-examples\todo-modern
	17 verbose Windows_NT 10.0.14393
	18 verbose argv "D:\\app\\develop\\nodejs\\node.exe" "D:\\app\\develop\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
	19 verbose node v6.10.2
	20 verbose npm  v4.5.0
	21 error code ELIFECYCLE
	22 error errno 1
	23 error @ build: `relay-compiler --src ./js/ --schema ./data/schema.graphql`
	23 error Exit status 1
	24 error Failed at the @ build script 'relay-compiler --src ./js/ --schema ./data/schema.graphql'.
	24 error Make sure you have the latest version of node.js and npm installed.
	24 error If you do, this is most likely a problem with the  package,
	24 error not with npm itself.
	24 error Tell the author that this fails on your system:
	24 error     relay-compiler --src ./js/ --schema ./data/schema.graphql
	24 error You can get information on how to open an issue for this project with:
	24 error     npm bugs
	24 error Or if that isn't available, you can get their info via:
	24 error     npm owner ls
	24 error There is likely additional logging output above.
	25 verbose exit [ 1, true ]

```

**Comment by taven-liu** [comment]
now, i use yarn reinstall the node_modules and then the project can running normally.
