### ISSUE TITLE
todo-modern: Cannot build project

### ISSUE THREAD

**Issue by object88** [relayjs/relay-examples#29]
When I attempt to build the project (either with `npm run build` or `yarn run build`, and after installing node_modules & updating the schema), I get this failure:

```
> @ build /Users/bropa18/Projects/relay-examples/todo-modern
> relay-compiler --src ./js/ --schema ./data/schema.graphql

HINT: pass --watch to keep watching for changes.
Parsed default in 0.12s

Writing default
TypeError: options.path.includes is not a function
    at Transformer.visitLinkedField (/Users/bropa18/Projects/relay-examples/todo-modern/node_modules/relay-compiler/bin/relay-compiler:1526:37)
    at Transformer._visit (/Users/bropa18/Projects/relay-examples/todo-modern/node_modules/relay-compiler/bin/relay-compiler:776:35)
    at /Users/bropa18/Projects/relay-examples/todo-modern/node_modules/relay-compiler/bin/relay-compiler:872:30
    at Array.forEach (native)
    at Transformer._map (/Users/bropa18/Projects/relay-examples/todo-modern/node_modules/relay-compiler/bin/relay-compiler:871:16)
    at /Users/bropa18/Projects/relay-examples/todo-modern/node_modules/relay-compiler/bin/relay-compiler:847:30
    at Array.forEach (native)
    at Transformer._traverseChildren (/Users/bropa18/Projects/relay-examples/todo-modern/node_modules/relay-compiler/bin/relay-compiler:841:31)
    at Transformer._traverse (/Users/bropa18/Projects/relay-examples/todo-modern/node_modules/relay-compiler/bin/relay-compiler:826:26)
    at Transformer.traverse (/Users/bropa18/Projects/relay-examples/todo-modern/node_modules/relay-compiler/bin/relay-compiler:765:26)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/bropa18/.nvm/versions/node/v5.10.1/bin/node" "/Users/bropa18/.nvm/versions/node/v5.10.1/bin/npm" "run" "build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! @ build: `relay-compiler --src ./js/ --schema ./data/schema.graphql`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'relay-compiler --src ./js/ --schema ./data/schema.graphql'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     relay-compiler --src ./js/ --schema ./data/schema.graphql
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bropa18/Projects/relay-examples/todo-modern/npm-debug.log
```

This is in the npm-debug logfile:

```
14 verbose stack Error: @ build: `relay-compiler --src ./js/ --schema ./data/schema.graphql`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/bropa18/.nvm/versions/node/v5.10.1/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/bropa18/.nvm/versions/node/v5.10.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

The version of relay-compiler that was installed is `1.0.0-rc.3`.

I am using node 5.10.1 and npm 3.8.3 (and yarn 0.24.6).

Any pointers where to take this?

**Comment by object88** [comment]
OK, I started experimenting with different versions of node, and `6.10.2` works.  Haven't tried other.  Is node 5 not compatible?

**Comment by jonirrings** [comment]
@object88 there is some syntax that node/babel-node support differs from each version. not knowing the detail.

from my experience, you'd better avoid the ambiguous syntax like 
use 
```js
import * as React from 'react'
```
instead of
```js
import React from 'react'
```
(just for a example, React with babel supports both though)
and use 
```js
const someGraphObjectType = new GraphQLObjectType({...});
export { someGraphObjectType };
```
instead of
```js
export const someGraphObjectType = new GraphQLObjectType({...});
```

**Comment by yuzhi** [comment]
Closing since it seems like this has been resolved

**Comment by object88** [comment]
Should there be a documentation note around this, if there is no code change?
