### ISSUE TITLE
Watchman Unknown option --no-pretty

### ISSUE THREAD

**Issue by the-noob** [relayjs/relay-examples#35]
When running `npm run build ` I'm getting a watchman error 
Tried reinstalling watchman a few times, no luck.

```
HINT: pass --watch to keep watching for changes.
ERROR: Unknown option --no-pretty

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= ERROR: Unknown option --no-pretty

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= ERROR: Unknown option --no-pretty

    at ChildProcess.<anonymous> (/home/the-noob/workspace/relay-examples/todo-modern/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by the-noob** [comment]
Had `NPM watchman` installed not https://facebook.github.io/watchman/, build went fine after installing FB one.
