### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by yarax** [relayjs/relay-examples#8]
TodoMVC `npm start` starts only GraphQL server
todo `npm start`:

```
ERROR in ./js/app.js
Module build failed: Error: Plugin 0 specified in "foreign" provided an invalid property of "_c"
    at Plugin.init (/home/roman/sandbox/relay-examples/todo/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/home/roman/sandbox/relay-examples/todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:144:12)
    at /home/roman/sandbox/relay-examples/todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:30
    at Array.map (native)
    at Function.normalisePlugins (/home/roman/sandbox/relay-examples/todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/home/roman/sandbox/relay-examples/todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at /home/roman/sandbox/relay-examples/todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:230:17
    at /home/roman/sandbox/relay-examples/todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:20
    at Array.map (native)
    at OptionManager.resolvePresets (/home/roman/sandbox/relay-examples/todo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
```

**Comment by kassens** [comment]
What versions of node/npm are you using?

A simple `npm install && npm start` works for me for the todo example.
```
$ npm -v
3.10.3
$ node -v
v6.5.0
```

**Comment by yarax** [comment]
http://pix.toile-libre.org/upload/original/1474470356.png

**Comment by kassens** [comment]
Sorry this fell of the radar a bit. Since this was so long ago, I'm closing this. If there's still issues we should re-open a new issue on the current code.
