### ISSUE TITLE
Error: Watchman was not found in PATH.

### ISSUE THREAD

**Issue by Ulimn** [relayjs/relay-examples#91]
As far as I know, this should be fixed and shouldn't happen, but I get an error: `Error: Watchman was not found in PATH.`.

I've done the following:

- clone the repo, cd into `todo`
- `yarn` 
- `yarn run update-schema`
- `yarn run build`

Tried it on two different PC's, Manjaro Linux, node version v11.10.0, npm version 6.8.0 and yarn 1.13.0. Also tried with LTS node (v10.15.1).

This is the output I get:
```
yarn run v1.13.0
$ relay-compiler --src ./js/ --schema ./data/schema.graphql
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
HINT: pass --watch to keep watching for changes.

Writing js
Created:
 - RemoveTodoMutation.graphql.js
 - MarkAllTodosMutation.graphql.js
 - AddTodoMutation.graphql.js
 - RenameTodoMutation.graphql.js
 - RemoveCompletedTodosMutation.graphql.js
 - ChangeTodoStatusMutation.graphql.js
 - appQuery.graphql.js
 - TodoListFooter_viewer.graphql.js
 - TodoList_viewer.graphql.js
 - Todo_viewer.graphql.js
 - Todo_todo.graphql.js
 - TodoApp_viewer.graphql.js
Unchanged: 0 files
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Emitted 'error' event at:
    at spawnError (/home/m/work/practice/relay-examples/todo/node_modules/fb-watchman/index.js:170:10)
    at ChildProcess.<anonymous> (/home/m/work/practice/relay-examples/todo/node_modules/fb-watchman/index.js:193:5)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Am I doing something wrong?

**Comment by alunyov** [comment]
@Ulimn thanks for reporting this.

Yes, we have an issue with the missing watchman: https://github.com/facebook/relay/issues/2617
I hope to get fix it by Friday.
